# Generated by Django 2.2.7 on 2019-11-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='test',
            field=models.CharField(default=2121, max_length=8),
            preserve_default=False,
        ),
    ]
